.TH catnest "1" "eweOS Project" "catnest"

.SH NAME
.TP
catnest \- A substitution for systemd-sysusers

.SH SYNOPSIS
	catnest [options] [CONFIGURATION]

.SH OPTIONS

.TP
.B
-h
.RS
show help text
.RE
.TP
.B
-r DIR
.RS
Set root to
.B DIR
.RE

.SH Difference from systemd-sysusers
.P
catnest doesn't create users or groups mentioned in 'm' entries implicitly.
.P
File paths in ID field are not supported.
.P
All GECOS strings need quotation, even if they don't
.B NOT
contain a blank character.
.P
gshadow files are not completely supported, but catnest will append to it
when needed. All existed group passwords will be
.B ERASED.

.SH SEE ALSO
.TP
systemd-sysusers(1)

.SH COPYRIGHT
.TP
Copyright (c) 2022-2023 Ziyao.
.TP
This program is distributed under MIT License and is a part of eweOS Project.
